### ISSUE TITLE
email encryption

### ISSUE THREAD

**Issue by 3rhbveox04e2ul** [CryptoverseCC/ethmail.cc#12]
Hello,
I read your explanation about email encryption trying to use the ETH public/private keys, or generating on-the-fly the PGP keys. Both methods indeed have more con's than pro's.

Other emailers, like Gmail thru FlowCrypt plug-in, Thunderbird or even ProtonMail defer such settings to the users. The suggestion would be to add an extra field in the contacts to be able to register their PGP Public key. My PGP Private Key to decrypt my emails, would be another setting in my personal profile, pointing to a local file.

Just a basic suggestion for an enhancement, if feasible, trying to minimize the resources.

**Comment by gkapkowski** [comment]
Hi, thanks for reaching out, it's already possible to use your own PGP keys through mailvelope or other extension, or even manually. What it's missing is automatic encryption/decryption in web client. 
If you connect ETHMail with your Thunderbird client you can use it as you mentioned. 

The solutions I was describing target users who either don't know PGP or for some reason don't want to manage their own keys outside form the wallet ones. They are based on what I see right now from user feedback. People value simplicity very much and they don't want to manage additional keys.
