### ISSUE TITLE
Outbound emails don't seem to work in various clients

### ISSUE THREAD

**Issue by smssoleimani** [CryptoverseCC/ethmail.cc#16]
Everything works via web.ethmail.cc but when trying to configure ETHmail on Gmail iOS or Mail on macOS the email downloads fine but sending doesn't work.

Following this [guide](https://ethmail.cc/howto.html). Password is not shown in the iOS screenshot but I did use it there and on both iOS and macOS the email downloads fine, it's outbound that doesn't work. Thoughts?

IMAP:
```
username: 0xYourEtheremAddress
password: the-key-you-generated-in-first-part
server: ethmail.cc
port: 143
security: STARTTLS
```

SMTP:
```
username: 0xYourEtheremAddress
password: the-key-you-generated-in-first-part
server: ethmail.cc
port: 587
security: STARTTLS
```

Key is setup correctly:
<img width="738" alt="Screen Shot 2021-04-11 at 8 07 14 PM" src="https://user-images.githubusercontent.com/27832853/114326197-9874dc00-9b01-11eb-8562-bcadff25d0ad.png">

Mail app on macOS:
<img width="676" alt="Screen Shot 2021-04-11 at 7 57 05 PM" src="https://user-images.githubusercontent.com/27832853/114326039-e806d800-9b00-11eb-8746-3c7c5935d159.png">

Gmail iOS:
![IMG_1344](https://user-images.githubusercontent.com/27832853/114326102-1dabc100-9b01-11eb-9a83-8e3ddd910956.PNG)
![IMG_1343](https://user-images.githubusercontent.com/27832853/114326103-1edcee00-9b01-11eb-8851-35539cd1097c.PNG)

Error on macOS:
<img width="531" alt="Screen Shot 2021-04-11 at 8 11 32 PM" src="https://user-images.githubusercontent.com/27832853/114326339-51d3b180-9b02-11eb-8124-a8a18834fef0.png">

Error on Gmail iOS:
![IMG_1345](https://user-images.githubusercontent.com/27832853/114326393-91020280-9b02-11eb-9d0c-7936d2c3bbec.jpg)

**Comment by gkapkowski** [comment]
Hi, thanks for the report I'll check the logs if I can find anything. I'm using ETHMail with my Gmail app on Android and sending messages worked for me just now so it doesn't look like something affecting everyone.

**Comment by gkapkowski** [comment]
Can you try now?

**Comment by smssoleimani** [comment]
Hi @gkapkowski it works now, thanks! What was the issue?

**Comment by gkapkowski** [comment]
It was a misconfiguration, I was performing some additional checks for clients that send hostname with helo command, those checks usually only apply when exchanging messages between servers but they were run when the email app connected. Normally this doesn't matter as most client use ip address instead of hostname.
