### ISSUE TITLE
same ETH wallet address identity.

### ISSUE THREAD

**Issue by OpenWorld00** [CryptoverseCC/ethmail.cc#17]
I can not switch to a one email to the other on the same ETH wallet address.

**Comment by gkapkowski** [comment]
Hi, thanks for reporting this but I need some more information to figure out what it going on. Are you facing issues when composing/sending emails or does your mailbox does not receive messages for all email addresses associated with your ethereum address?

**Comment by OpenWorld00** [comment]
![Screenshot from 2021-04-24 23-21-19](https://user-images.githubusercontent.com/56146404/115983331-5b730580-a555-11eb-8afd-7edbcadafd41.png)

I can't switch from the two Identities. So you can not switch over to (0x034c9e41bafc2278c9bea9cf1ad8915c019b200e) email

**Comment by gkapkowski** [comment]
There si not need to switch those identities, bot of them are available.
When composing email you can just choose appropriate email:
![Screenshot from 2021-04-26 09-06-59](https://user-images.githubusercontent.com/114996/116042660-f6abce00-a66e-11eb-907f-bd5878eb915c.png)

And when you receive messages to any of them they will appear in your inbox

**Comment by gkapkowski** [comment]
If you want to login using different ethereum address you need to log out and switch to desired address in your wallet
