### ISSUE TITLE
error on send

### ISSUE THREAD

**Issue by jpritikin** [CryptoverseCC/ethmail.cc#2]
I tried to send a test email to myself,

![Screenshot from 2020-05-04 16-09-33](https://user-images.githubusercontent.com/2002771/81009025-dd888c80-8e21-11ea-8022-e3d9c8f37de2.png)

Maybe sending email is not so important.

**Comment by gkapkowski** [comment]
That's interesting, this is a message from my own spam prevention settings. It looks like the IP you are connecting from is listed in spamhaus. Depending on how your ISP assigns IP addresses you might just got unlucky and get one after someone used it to send spam.

This message is generated when your local client (mail app) tries to upload email to ETHMail server.

You can try using different ISP or maybe VPN. 

You can also send email from [web.ethmail.cc](https://web.ethmail.cc/), this will allow you to check if emails going from ETHMail server to your email server will go through.

**Comment by jpritikin** [comment]
OK, well it's not important. I think the ability to receive mail from ethmail.cc is much more interesting that the ability to send.
