### ISSUE TITLE
API or a possible way to send email from backend

### ISSUE THREAD

**Issue by intergalacticspacehighway** [CryptoverseCC/ethmail.cc#20]
Thanks for the cool project. I had been looking for a way to send an email from backend. Is it possible?
I would need to authenticate from backend. I am not really sure how would that work. Thanks!

**Comment by gkapkowski** [comment]
Hi, you can use any SMTP library to send emails from your backend servers. ETHMail is a classical email server.
All you need is to generate password for your account to be able to send emails from it. You can go it at https://keys.cryptoverse.cc/keys/ - login with the account you want to use for sending emails, create need access key (this will be your password), and configure your backend to use the ethereum address as username and generated access key as password.

**Comment by intergalacticspacehighway** [comment]
Great. Thank you!
