### ISSUE TITLE
python api access example

### ISSUE THREAD

**Issue by benjyz** [CryptoverseCC/ethmail.cc#3]
tried access with this python script and get `[Errno 61] Connection refused`

```
from smtplib import SMTP
import datetime

debuglevel = 0

server = "ethmail.cc"

smtp = SMTP()
smtp.set_debuglevel(debuglevel)
smtp.connect(server, 26)
uname = "0x..."
pw = "..."
r = smtp.login(uname, pw)
print (r)

```

**Comment by gkapkowski** [comment]
Your port is invalid, the server only accepts connections on submission port 587 (and 25 but for that you need to have properly configured SMTP server with hostname, PTR record etc.)

**Comment by gkapkowski** [comment]
And you need `smtp.starttls()` before `smtp.login(...)`

**Comment by gkapkowski** [comment]
Can you share what you are building with ETHMail? :)

**Comment by benjyz** [comment]
was just testing for now. I somehow can't regenerate the "api keys".

**Comment by gkapkowski** [comment]
You can only generate new keys at https://auth.cryptoverse.cc/keys/mykeys
