### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by benjyz** [CryptoverseCC/ethmail.cc#4]
cool project, some more general info/faq would be helpful to understand what it is. the backend is a standard SMTP server or how does it work?

**Comment by gkapkowski** [comment]
Yes, it's standard SMTP server with couple of custom components.

What other questions would you like to see answered in FAQ ?

**Comment by benjyz** [comment]
some ideas...

how does key-generation/signatures work?

are emails encrypted by default?

how much trust is involved in terms of the SMTP hosting compared to traditional email?

plans to opensource components?

**Comment by gkapkowski** [comment]
Thanks, I'll prepare answers to those and add FAQ section to the webpage.

**Comment by benjyz** [comment]
@gkapkowski read the FAQ. thanks. what does this mean not sure?

`There are no blockchain complements except for ENS/UnstoppableDomain name resolution.`

**Comment by gkapkowski** [comment]
typo, should be `components` :/
I wanted to say that the whole system is only using blockchain for ENS/UnstoppableDomains resolution, all other functions do not depend on it. It matters when blockchain is congested and node might be out of sync. You could have situation when ENS entries are being changed but the node I'm using doesn't know about it and it may result in delivering emails to the wrong mailbox.

**Comment by benjyz** [comment]
could one somehow emulate subusers `alice@example.com` with ENS subdomains or sth like this?

**Comment by gkapkowski** [comment]
Yes, this is the second part of ENS support I was planning to add for organizations/communities (eg. DAOs).
To have `subdomain@domain.xyz` for `subdomain.domain.eth` or something similar.

It's possible, not yet implemented.

**Comment by gkapkowski** [comment]
Checkout https://community.cryptoverse.cc/ for other ideas I have.
