### ISSUE TITLE
Problem with email signatures

### ISSUE THREAD

**Issue by PaulUD** [CryptoverseCC/ethmail.cc#5]
Signatures seem to be fine when added **manually** but not when trying to **automate** them in user Identity.

All signatures I tried were rejected.

**Comment by gkapkowski** [comment]
I'm not sure I understand, what do you mean by "Signatures"?
Can you describe what are you trying to automate?

**Comment by PaulUD** [comment]
@gkapkowski please see screenshot.

![Signatures failing](https://user-images.githubusercontent.com/60640581/84244977-11d02680-ab0d-11ea-8f1f-bc01964c3db8.png)

**Comment by gkapkowski** [comment]
Oh, ok, I'll take a look at it.

**Comment by gkapkowski** [comment]
@PaulUD Fixed
