### ISSUE TITLE
Login protocol spec

### ISSUE THREAD

**Issue by benjyz** [CryptoverseCC/ethmail.cc#6]
I see at login there is a signature of the following"Cryptoverse Login - auth.cryptoverse.cc|z....."
Is there a spec of this protocol somewhere? The server sends a challenge and the client signs this? What do the server end points look like?

In python this might look like this maybe
```
@app.route('/web3signup', methods=['POST'])
def account_signup:
#init account based data

@app.route('/web3login', methods=['GET'])
def account_login:
#request account based data

```

**Comment by gkapkowski** [comment]
Cryptoauth.io a.k.a Cryptoverse Login (I know it's confusing)

The protocol used here is OpenID Connect https://openid.net 

ETHMail is implemented in a way that is uses Cryptoverse Login as Identity Provider - meaning, when user comes in and wants to login to ETHMail web client, he/she is redirected to Cryptoverse Login. There the user confirms his/her identity (Ethereum address) and Cryptoverse Login redirects the user back to ETHMail with confirmation of this identity. ETHMail trusts Cryptoverse Login server to do a good job of confirming user identity.

OpenID Connect is based on oAuth2 and clients of Identity Provider (server) require client Id and secret to use it.

You can see the same mechanism at https://community.cryptoverse.cc - here Discourse instance has a OpenID Connect plugin installed and is configured to use Cryptoverse Login to log-in users.

I also experimented with WordPress (it also have OpenID Connect plugin available, though I had to modify it slightly) - https://cryptotraders.blog
