### ISSUE TITLE
Propose this dapp for the district0x registry

### ISSUE THREAD

**Issue by diegovdc** [CryptoverseCC/ethmail.cc#8]
Hello, I just had this same idea, and was doing a bit of research to see if someone had already though about something like this. I think ETHmail is project is pretty awesome and has plenty of room to grow.

I recently learned about this registry https://github.com/district0x/district-proposals.  You can submit a proposal and if accepted get a prize (which I am sure could help you fund this and a more elaborate version), plus you'd get the exposure.

I might consider submitting a similar idea if you don't, but perhaps you are interested and then you'd save me a lot of work :) ...  (also I am working on other ideas as well)

**Comment by gkapkowski** [comment]
Hey!  

I decided not to add ETHMail as a proposal there, I don't feel it's a good match for what I plan to do.

Thanks for telling me about it, I appreciate it.
